export const fonts = [
  { value: "AlQuranAli", label: "القرآن علي" },
  { value: "Arabic", label: "عربي" },
  { value: "FS_Arabic", label: "عربي ف" },
  { value: "KFGQPCUthmanTaha", label: "عثمان طه" },
  { value: "KFGQPCDot", label: "عثماني منقّط" },
  { value: "Kamel", label: "كامل" },
  { value: "MuhammadiQuranic", label: "محمدي" },
  { value: "Outlined", label: "مخطط" },
  { value: "Sada", label: "صدى" },
  { value: "Samim", label: "صميم" },
  { value: "UthmanTNB", label: "عثمان جديد ب" },
  { value: "UthmanTN", label: "عثمان جديد" },
  { value: "UthmanTSB", label: "عثمان س ب" },
  { value: "UthmanTS", label: "عثمان س" },
  { value: "Zakhrfa", label: "زخرفة" },
  { value: "ZakhrfaOutline", label: "زخرفة مخططة" },
  { value: "MyLotus", label: "ماي لوتس" },
];
